export const commonFiles = [
  "commons/authModal.ts",
  "commons/common.ts",
  "commons/deleteDialog.ts",
  "commons/donationBox.ts",
  "commons/followButton.ts",
  "commons/genres.ts",
  "commons/imageUploader.ts",
  "commons/landingPage.ts",
  "commons/seriesDrawer.ts",
  "commons/seriesFooter.ts",
  "commons/seriesReader.ts",
  "commons/tagForm.ts",
  "commons/topNav.ts",
];

export const nonCommonFiles = [
  "about.ts",
  "account.ts",
  "consoleChapterList.ts",
  "consoleCreateChapter.ts",
  "consoleCreateSeries.ts",
  "consoleEditChapter.ts",
  "consoleEditSeries.ts",
  "consoleSeriesList.ts",
  "dashboard.ts",
  "genre.ts",
  "home.ts",
  "profile.ts",
  "search.ts",
  "settings.ts",
  "support.ts",
  "translate.ts",
  "viewChapter.ts",
  "viewChapters.ts",
];
