name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: kyllolive/epico-translations
          ref: main
          token: ${{ secrets.MY_PAT }}

      - name: Copy translations folder
        run: cp -R ${{GITHUB_WORKSPACE}}src/translations/* epico-translations/commons/

      - name: Push changes
        run: git add . && git commit -m "Add translations" && git push origin my-feature

      - name: Create Pull Request
        uses: actions/create-pull-request@v4
        with:
          title: "Add translations"
          head: "my-feature"
          base: "main"
          body: "This pull request adds a translations folder to the target repository."
          repository: kyllolive/epico-translations
          token: ${{ secrets.MY_PAT }}
