name: Create PR

on:
  push:
    branches:
      - main

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update translations
        run: |
          git remote add target https://github.com/kyllolive/epico-translations
          git fetch target
          git checkout -b update-translations target/main
          cp -r translations/* epico-translations/translations/
          git add -A
          git commit -m "Update translations"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update translations
          head: update-translations
          base: main
          labels: translations
          token: ${{ secrets.MY_PAT }}
