name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_PAT }}
        with:
          source_file: "src/translations"
          destination_repo: "kyllolive/epico-translations"
          destination_folder: "test-dir"
          user_email: "kyllolive@gmail.com"
          user_name: "kyllolive"
          commit_message: "A custom message for the commit"
