name: CI

on:
  push:
    branches:
      - feat/push-translation

jobs:
  update_translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: kyllolive/nextjs-octokit-demo
          ref: main
          path: nextjs-octokit-demo

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: kyllolive/octokit-demo
          ref: main
          path: octokit-demo

      - name: Check contents of target repository
        run: |
          cd octokit-demo
          if [ -d "src/translations" ]; then
            echo "Target repository contains src/translations folder."
          else
            echo "Target repository does not contain src/translations folder."
          fi

      - name: Update translations folder
        run: |
          cd octokit-demo
          rm -rf src/translations
          cp -r ../nextjs-octokit-demo/src/translations src/

      - name: Push changes
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: update_translations
          force: true
          folder: octokit-demo
