name: Update translations

on:
  push:
    branches:
      - feat/push-translation

env:
  GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          ref: main
          repository: kyllolive/octokit-demo
          token: ${{ env.GITHUB_TOKEN }}

      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: kyllolive/nextjs-octokit-demo
          token: ${{ env.GITHUB_TOKEN }}
          ref: main
          path: ../nextjs-octokit-demo

      - name: Update translations folder
        run: |
          rm -rf src/translations
          cp -r ../nextjs-octokit-demo/src/translations src/

      - name: Create branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b update-translations
          git add src/translations
          git commit -m "Update translations folder"
          git push -u origin update-translations

      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          title: "Update translations folder"
          body: "This pull request updates the translations folder with the latest changes."
          head: update-translations
          base: main
          token: ${{ env.GITHUB_TOKEN }}
