name: CI

on:
  push:
    branches:
      - feat/push-translation

jobs:
  update_translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: kyllolive/nextjs-octokit-demo
          ref: main
          path: nextjs-octokit-demo
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: kyllolive/octokit-demo
          ref: main
          path: octokit-demo
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Check contents of target repository
        run: |
          cd octokit-demo
          if [ -d "src/translations" ]; then
            echo "Target repository contains src/translations folder."
          else
            echo "Target repository does not contain src/translations folder."
          fi

      - name: Update translations folder
        run: |
          cd octokit-demo
          rm -rf src/translations
          cp -r ../nextjs-octokit-demo/src/translations src/

      # - name: Set up Git
      #   run: |
      #     cd octokit-demo
      #     git config --global user.email "actions@github.com"
      #     git config --global user.name "GitHub Actions"

      - name: Create branch
        run: |
          cd octokit-demo
          git init
          git remote remove origin
          git remote add origin https://github.com/kyllolive/octokit-demo.git
          git config --global user.email "kyllolive@gmail.com"
          git config --global user.name "kyllolive"
          git checkout -b update-translations 
          git add src/translations
          git commit -m "Update translations folder"
          git push --set-upstream origin update-translations
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: create pull request
        run: gh pr create -B update-translations -H main --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     title: "Update translations folder"
      #     body: "This pull request updates the translations folder with the latest changes."
      #     branch: update-translations
      #     base: main
      #     token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
