name: Update Translation Files

on:
  push:
    branches:
      - feat/push-translation

env:
  GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Clone target repository
        uses: actions/checkout@v2
        with:
          ref: main
          repository: kyllolive/octokit-demo
          token: ${{ env.GITHUB_TOKEN }}

      - name: Create branch
        run: |
          git checkout -b update-translations
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      - name: List contents of source translations directory
        run: |
          echo "Contents of source translations directory:"
          ls ../nextjs-octokit-demo/src

      - name: Update translations folder
        run: |
          rm -rf src/translations
          cp -r ../nextjs-octokit-demo/src/translations src/

      - name: Commit changes
        run: |
          git add src/translations
          git commit -m "Update translations folder"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: update-translations
          token: ${{ env.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Update translations folder
          title: Update translations folder
          body: |
            This pull request updates the translations folder in the target repository.

          labels: update, translations
          reviewers: kyllolive@gmail.com
          token: ${{ env.GITHUB_TOKEN }}
